name: qr_code_attendnce_admin_side
description: QR Code Attendance System - Admin Side
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.2.0
  intl: ^0.19.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint_core: ^0.7.0 # Add this line with a newer version
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
